### ISSUE TITLE
https certificate expired 

### ISSUE THREAD

**Issue by Annagramma** [DemocraciaEnRed/ecuador#13]
Can't access the site: **NET::ERR_CERT_DATE_INVALID**

![image](https://cloud.githubusercontent.com/assets/4205060/14742277/a316b8cc-0871-11e6-99a2-de050449bc2f.png)

**Comment by gvilarino** [comment]
This probably has to do with the way we generated this cert: I believe we did this through `letsencrypt.org` and they expire after 2 months. I think I read somewhere that they now support automatic-renovation.

I believe @slifszyc did this. Could you comment on this?
