### ISSUE TITLE
Actualizar el text de la cover

### ISSUE THREAD

**Issue by Annagramma** [DemocraciaEnRed/ecuador#6]
Construyamos propuestas para el próximo presidente

Jóvenes líderes de Ecuador elaboran y debaten propuestas de gobierno para los candidatos a la Presidencia de la República y la Asamblea Nacional del periodo 2017-2021. La Fundación Ciudadanía y Desarrollo y la Embajada de Canadá en Ecuador acompañan la iniciativa.
¡Conocé las propuestas!

**Comment by snakefooc** [comment]
Status

![espacio joven](https://cloud.githubusercontent.com/assets/1830970/12794658/ef35bce6-ca94-11e5-89c2-96e79b2a6381.jpg)
