### ISSUE TITLE
Arreglar estilos de la vista del Proyecto

### ISSUE THREAD

**Issue by mjlescano** [DemocraciaEnRed/ecuador#7]
- No hay coherencia en los tamaños de las fonts.
- La combinación `Open Sans` en los títulos y `Noto Serif` en los párrafos no nos gusta como queda.
- Mostrar de otra forma las fotos (opcional) ¿Hay alternativas?
- La relación del tamaño entre el Título y el párrafo no está bien, ¿el título es muy grande?

**Comment by snakefooc** [comment]
h1 Quicksand Bold 64px
h2 Quicksand Bold 36px
h3 Quicksand Bold 28px
h4 Quicksand Bold 24px
h5 Quicksand Bold 18px
h6 Quicksand Regular 13px

p Open Sans 16px

Descripción del projecto
p Tora 16px
